require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AllowancesController do

  # This should return the minimal set of attributes required to create a valid
  # Allowance. As you add validations to Allowance, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "amount" => "1.5", "started_at" => Time.zone.now }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AllowancesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all allowances as @allowances" do
      allowance = Allowance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:allowances).should eq([allowance])
    end
  end

  describe "GET show" do
    it "assigns the requested allowance as @allowance" do
      allowance = Allowance.create! valid_attributes
      get :show, {:id => allowance.to_param}, valid_session
      assigns(:allowance).should eq(allowance)
    end
  end

  describe "GET new" do
    it "assigns a new allowance as @allowance" do
      get :new, {}, valid_session
      assigns(:allowance).should be_a_new(Allowance)
    end
  end

  describe "GET edit" do
    it "assigns the requested allowance as @allowance" do
      allowance = Allowance.create! valid_attributes
      get :edit, {:id => allowance.to_param}, valid_session
      assigns(:allowance).should eq(allowance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Allowance" do
        expect {
          post :create, {:allowance => valid_attributes}, valid_session
        }.to change(Allowance, :count).by(1)
      end

      it "assigns a newly created allowance as @allowance" do
        post :create, {:allowance => valid_attributes}, valid_session
        assigns(:allowance).should be_a(Allowance)
        assigns(:allowance).should be_persisted
      end

      it "redirects to the created allowance" do
        post :create, {:allowance => valid_attributes}, valid_session
        response.should redirect_to(Allowance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved allowance as @allowance" do
        # Trigger the behavior that occurs when invalid params are submitted
        Allowance.any_instance.stub(:save).and_return(false)
        post :create, {:allowance => { "amount" => "invalid value" }}, valid_session
        assigns(:allowance).should be_a_new(Allowance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Allowance.any_instance.stub(:save).and_return(false)
        post :create, {:allowance => { "amount" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested allowance" do
        allowance = Allowance.create! valid_attributes
        # Assuming there are no other allowances in the database, this
        # specifies that the Allowance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Allowance.any_instance.should_receive(:update_attributes).with({ "amount" => "1.5" })
        put :update, {:id => allowance.to_param, :allowance => { "amount" => "1.5" }}, valid_session
      end

      it "assigns the requested allowance as @allowance" do
        allowance = Allowance.create! valid_attributes
        put :update, {:id => allowance.to_param, :allowance => valid_attributes}, valid_session
        assigns(:allowance).should eq(allowance)
      end

      it "redirects to the allowance" do
        allowance = Allowance.create! valid_attributes
        put :update, {:id => allowance.to_param, :allowance => valid_attributes}, valid_session
        response.should redirect_to(allowance)
      end
    end

    describe "with invalid params" do
      it "assigns the allowance as @allowance" do
        allowance = Allowance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Allowance.any_instance.stub(:save).and_return(false)
        put :update, {:id => allowance.to_param, :allowance => { "amount" => "invalid value" }}, valid_session
        assigns(:allowance).should eq(allowance)
      end

      it "re-renders the 'edit' template" do
        allowance = Allowance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Allowance.any_instance.stub(:save).and_return(false)
        put :update, {:id => allowance.to_param, :allowance => { "amount" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested allowance" do
      allowance = Allowance.create! valid_attributes
      expect {
        delete :destroy, {:id => allowance.to_param}, valid_session
      }.to change(Allowance, :count).by(-1)
    end

    it "redirects to the allowances list" do
      allowance = Allowance.create! valid_attributes
      delete :destroy, {:id => allowance.to_param}, valid_session
      response.should redirect_to(allowances_url)
    end
  end

end
